from functions.get_files_info import get_files_info
from functions.get_file_content import get_file_content
print("Results:")

result1 = get_file_content("calculator", "main.py")
print(result1)
print("----------------------------------------------")
result2 = get_file_content("calculator", "pkg/calculator.py")
print(result2)
print("----------------------------------------------")
result3 = get_file_content("calculator", "/bin/cat")
print(result3)
print("----------------------------------------------")
result4 = get_file_content("calculator", "pkg/does_not_exist.py")
print(result4)
print("----------------------------------------------")

# result1 = get_files_info("calculator", ".")
# print(result1)
# print("----------------------------------------------")
# result2 = get_files_info("calculator", "pkg")
# print(result2)
# print("----------------------------------------------")
# result3 = get_files_info("calculator", "/bin")
# print(result3)
# print("----------------------------------------------")
# result4 = get_files_info("calculator", "../")
# print(result4)